# Configuration
kafka:
  bootstrap_servers: "localhost:9092"
  topic: "weather_hourly"

database:
  host: "localhost"
  port: 5432
  dbname: "weather_pipeline"
  user: "YOUR_USERNAME"
  password: "YOUR_PASSWORD"

api:
  provider: "openweather"
  api_key: "YOUR_API_KEY"

